[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm exec prisma generate",
  "pnpm --filter api run build"
]

[start]
cmd = "node apps/api/dist/index.js"
